### ISSUE TITLE
Embed tagged signer in tkey-ssh-agent

### ISSUE THREAD

**Issue by mchack-work** [tillitis/tkey-ssh-agent#106]
Like in tkey-sign-cli we want to embed the pre-compiled signer app directly in the repo. We keep all the build scripts to rebuild stuff, obviously, and still use that in the CI.

We keep a digest to be sure nothing changed, always checked with CI.

Embedding the binary in the repo enables go install.

**Comment by mchack-work** [comment]
Tested on Linux. Works fine.

Needs testing on Windows and macOS.

**Comment by dehanj** [comment]
Works on macos.

I miss a few things.
- More instructions about go install, and clearer in the readme that it is supported and how to do it.
- Maybe an example of a service-config one can enable (at least for linux) to get it running as it does when we pack it in deb/brew-packages. 
- I also think we should point to our official instructions on tillitis.se
- If we do the above point, we can most likely remove a bit of the info from this readme. It feels like a lot of info here.
