### ISSUE TITLE
Non-standard GPLv2 LICENSE file

### ISSUE THREAD

**Issue by jas4711** [tillitis/tkey-ssh-agent#122]
Hi.  The LICENSE file seem to refer to GPLv2, but it looks rather modified compared to most versions of GPLv2 that I know.  Where did you get this file from?

The license on the license does not permit modifications.  If indeed the canonical GPLv2 is intended, how about importing it from the publisher FSF?

I suggest using the following version, it has been modified to avoid the stale postal address found in earlier GPLv2 license texts.

https://git.savannah.gnu.org/cgit/gnulib.git/plain/doc/COPYINGv2

Thanks,
/Simon

**Comment by mchack-work** [comment]
Official license now BSD-2-clause.
