### ISSUE TITLE
Break out ssh-agent

### ISSUE THREAD

**Issue by mchack-work** [tillitis/tkey-ssh-agent#88]
Make tkey-ssh-agent standalone in its own repo.

Probably rename -apps to tkey-ssh-agent to keep the stars for Homebrew.

**Comment by mchack-work** [comment]
It's now alone in repo but renaming repo will have to wait until we announce the plans widely.

**Comment by bbigras** [comment]
Any progress on renaming the repo?

**Comment by dehanj** [comment]
Just did it. For context, we were look into if it would give us problems with our brew formula, but apparently GitHub redirects to the new name automatically.
